
PY3=python3

#
# For a great explanation of how to design your unit test directory
# structure and then call your unit tests, see the following post:
#
#  https://stackoverflow.com/questions/1896918/running-unittest-with-typical-test-directory-structure
#
test:
	$(PY3) -m unittest discover

# --- END --- #

