language: python
python: 
  - "3.7"
  - "3.8"
before_install: 
  - sudo apt-get install -y libasound2-dev
script: 
 - flake8 easy_music_generator/__init__.py
 - cd easy_music_generator && python -m unittest discover
