language: python

python: 
  - "3.8"

before_install: 
  - sudo apt-get install -y libasound2-dev

#
# List of commands to run before the main script
#
before_script: 
 - flake8 easy_music_generator/__init__.py

script: 
 - coverage run -m unittest discover

after_success:
  - coverage report
  - coveralls
